# Generated by Django 5.0.6 on 2024-06-21 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_remove_album_musician_album_author'),
        ('musicianAp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='musicianAp.musician'),
        ),
    ]
